"""S12 ABI rejection, actual host branch simulation and reviewed SASS mutations.

The CPU CUDA shim exercises host coverage/failure handling only. It never
substitutes for target compilation, actual device execution or family B3.
"""
import copy
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parents[1]
sys.path.insert(0, str(ROOT))
from auditors import async_copy_validation as adapter
from auditors.async_copy import audit_sass, kernel_symbol

CONTRACT = json.loads((ROOT/'contracts/async_copy.json').read_text())
PROFILE = json.loads((ROOT/'contracts/async_copy_validation_profiles_v1.json').read_text())['profiles'][0]
SASS = REPO/'results/gh200_resource_campaign/20261001-resource-suite-v2/implementation/target-compile-async-copy-a/diagnostics/async_copy/sass.txt'

# CPU-only CUDA API shim. Device values are enumerated, not generated by the C++
# checksum oracle. Corruptions target independently allocated output components.
SHIM = r'''
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
#include "REFERENCE_PATH"
namespace gh {
using u64=unsigned long long;
struct Stamp {u64 begin_ns,end_ns,begin_cycle,end_cycle;unsigned smid;};
struct Observation {std::vector<Stamp> stamps;double event_ms=0;u64 errors=0,checked_elements=0;std::string method,input_conditions;};
struct Prop {int multiProcessorCount=2;size_t sharedMemPerBlockOptin=227328;};
struct Device {Prop prop;};
Device device(){return {};}
void emit_device(const Device&){std::cout<<"{\"schema_version\":2,\"type\":\"device\",\"cc\":\"9.0\",\"name\":\"CPU shim GH200\",\"uuid\":\"GPU-00000000-0000-0000-0000-000000000000\",\"sms\":2,\"driver_version\":12090,\"runtime_version\":12090,\"registers_per_sm\":65536,\"smem_per_sm_bytes\":233472,\"smem_per_cta_optin_bytes\":227328}\n";}
std::string quote(const std::string& s){return "\""+s+"\"";}
u64 integer(const char* s,u64 lo,u64 hi){char* e;auto x=std::strtoull(s,&e,10);if(*e||x<lo||x>hi)throw std::runtime_error("integer");return x;}
template<class F> int warmup(F){throw std::runtime_error("FORBIDDEN warmup");}
template<class... T> void emit_trial(T...){throw std::runtime_error("FORBIDDEN trial");}
}
constexpr unsigned ac_threads=128;
constexpr gh::u64 ac_array_bytes=8388608;
int selected_width=0,selected_stages=0;
template<int W,int S,bool C> void ac_pipeline(){selected_width=W;selected_stages=S;}
struct cudaFuncAttributes {int numRegs=32;size_t sharedSizeBytes=0,localSizeBytes=0;};
struct dim3 {unsigned x;dim3(unsigned n):x(n){}};
using cudaEvent_t=int;
constexpr int cudaMemcpyHostToDevice=0,cudaMemcpyDeviceToHost=1;
#define GH_CUDA(call) do{if((call)!=0)throw std::runtime_error("CUDA shim failure: " #call);}while(0)
int cudaFuncGetAttributes(cudaFuncAttributes* a,const void* f){*a={};reinterpret_cast<void(*)()>(const_cast<void*>(f))();return 0;}
int cudaOccupancyMaxActiveBlocksPerMultiprocessor(int* o,const void*,unsigned,size_t){*o=4;return 0;}
template<class T> int cudaMalloc(T** p,size_t n){*p=static_cast<T*>(std::malloc(n));return *p?0:1;}
int cudaMemcpy(void* a,const void* b,size_t n,int){std::memcpy(a,b,n);return 0;}
int cudaMemset(void* a,int value,size_t n){std::memset(a,value,n);return 0;}
int cudaFree(void* p){std::free(p);return 0;}
int cudaEventCreate(int* p){*p=0;return 0;} int cudaEventRecord(int){return 0;}
int cudaEventSynchronize(int){return 0;} int cudaEventDestroy(int){return 0;}
int cudaEventElapsedTime(float* p,int,int){*p=0;return 0;}
int cudaLaunchKernel(const void*,dim3 grid,dim3,void** args,size_t){
 static int launch=0;++launch;
 const std::string fail=std::getenv("S12_STUB_FAILURE")?std::getenv("S12_STUB_FAILURE"):"";
 if(fail=="cuda"||(fail=="cuda_second"&&launch==2))return 1;
 auto input=*static_cast<unsigned**>(args[0]);int steps=*static_cast<int*>(args[1])*8;
 auto stamps=*static_cast<gh::Stamp**>(args[2]);auto sums=*static_cast<unsigned**>(args[3]);
 auto finals=*static_cast<unsigned**>(args[4]);auto trace=*static_cast<unsigned**>(args[5]);
 const unsigned words=selected_width/4;
 for(unsigned b=0;b<grid.x;++b){
  stamps[b]={0,0,0,0,b%2};
  for(unsigned t=0;t<128;++t){
   unsigned sum=0;
   for(int step=0;step<steps;++step)for(unsigned word=0;word<words;++word){
    size_t address=((size_t(b)*128+(t+1)%128+size_t(step)*grid.x*128)*words+word)%(8388608/4);
    unsigned value=input[address];sum+=value;
    if(trace)trace[((size_t(b)*128+t)*steps+step)*words+word]=value;
   }
   sums[size_t(b)*128+t]=sum;
   for(int step=0;step<steps;++step)for(unsigned word=0;word<words;++word){
    size_t address=((size_t(b)*128+t+size_t(step)*grid.x*128)*words+word)%(8388608/4);
    finals[((size_t(b)*selected_stages+step%selected_stages)*128+t)*words+word]=input[address];
   }
  }
 }
 if(fail=="stamp")stamps[grid.x-1].end_cycle=~gh::u64(0);
 if(fail=="smid")stamps[grid.x-1].smid=2;
 if(fail=="trace")trace[(size_t(grid.x)*128*steps)*words-1]^=1;
 if(fail=="sum")sums[size_t(grid.x)*128-1]^=1;
 if(fail=="slot")finals[size_t(grid.x)*selected_stages*128*words-1]^=1;
 if(fail=="many")for(unsigned t=0;t<128;++t)sums[t]^=1;
 return 0;
}
'''


def unique_object(pairs):
    result={}
    for k,v in pairs:
        if k in result: raise ValueError('duplicate JSON key '+k)
        result[k]=v
    return result


class AsyncCopyValidationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.temp=tempfile.TemporaryDirectory()
        source=(ROOT/'probes/async_copy.cu').read_text()
        host=source[source.index('struct AcCase'):]
        path=Path(cls.temp.name)/'host.cpp'
        path.write_text(SHIM.replace('REFERENCE_PATH',str(ROOT/'common/async_copy_reference.hpp'))+host)
        cls.binary=Path(cls.temp.name)/'host'
        subprocess.run(['g++','-std=c++17','-O2',str(path),'-o',str(cls.binary)],check=True,capture_output=True,timeout=30)

    @classmethod
    def tearDownClass(cls): cls.temp.cleanup()

    def run_host(self,case,failure='',seed=4294967291):
        env=dict(os.environ,S12_STUB_FAILURE=failure)
        run=subprocess.run([str(self.binary),'validate-only',case['id'],PROFILE['id'],str(seed)],text=True,capture_output=True,env=env,timeout=10)
        rows=[json.loads(line,object_pairs_hook=unique_object) for line in run.stdout.splitlines()]
        self.assertEqual(len(rows),2,run.stderr)
        return run,rows

    def test_real_host_all_24_cases(self):
        for case in CONTRACT['cases']:
            with self.subTest(case=case['id']):
                run,(device,row)=self.run_host(case)
                self.assertEqual(run.returncode,0,run.stderr)
                result=adapter.validate_validation(device,row,case,PROFILE,4294967291)
                self.assertEqual(result['target_launches'],2)
                self.assertEqual(result['output_evidence_kind'],'error_count_only')
                self.assertFalse(result['performance_eligible'])
                self.assertEqual(adapter.validation_argv('bin/probe',case,PROFILE,0),['bin/probe','validate-only',case['id'],'short_copy_1_2','0'])

    def test_actual_host_corruption_and_partial_failure(self):
        case=CONTRACT['cases'][-1]
        for failure in ('stamp','smid','trace','sum','slot','many','cuda','cuda_second'):
            with self.subTest(failure=failure):
                run,(device,row)=self.run_host(case,failure)
                self.assertNotEqual(run.returncode,0)
                self.assertGreater(row['errors'],0)
                self.assertEqual(len(row['target_launches']),2 if failure=='cuda_second' else 1)
                self.assertLessEqual(sum(line.startswith('length=') for line in run.stderr.splitlines()),8)
                if failure in ('stamp','smid','cuda','cuda_second'):self.assertFalse(row['checks'][-1]['completed'])
                with self.assertRaises(ValueError):adapter.validate_validation(device,row,case,PROFILE,4294967291)

    def test_adapter_rejects_tampered_receipts(self):
        case=CONTRACT['cases'][-1];_,(device,original)=self.run_host(case)
        mutations=[lambda r:r.update(type='s12_short_validation'),lambda r:r.update(validation_schema_version=True),
                   lambda r:r.update(errors=1),lambda r:r.update(errors=False),lambda r:r.update(warmup_executed=True),
                   lambda r:r.update(pilot_executed=True),lambda r:r.update(performance_eligible=True),
                   lambda r:r.update(scope='one_cta'),lambda r:r.update(blocks=1),lambda r:r.update(seed=1),
                   lambda r:r['target_launches'].pop(),lambda r:r['checks'].pop(),
                   lambda r:r['target_launches'][1].update(iterations=1),lambda r:r['target_launches'][0].update(iterations=True),
                   lambda r:r['target_launches'][0].update(input_profile='uniform'),
                   lambda r:r['checks'][1].update(launch_index=0),lambda r:r['checks'][0].update(completed=False),
                   lambda r:r['checks'][0].update(reference_sha256='0'*64),lambda r:r['checks'][0].update(comparison='profile_bounded'),
                   lambda r:r['checks'][0]['verified_CTA_ids'].pop(),lambda r:r['checks'][0].update(verified_CTA_ids=[0]*r['blocks']),
                   lambda r:r['checks'][0].update(output_artifacts=[{}]),
                   lambda r:r['resource_identity'].update(kernel_symbol='wrong'),lambda r:r['resource_identity'].update(dynamic_smem_bytes=0),
                   lambda r:r['resource_identity'].update(static_smem_bytes=512),lambda r:r['resource_identity'].update(local_size_bytes=4),
                   lambda r:r['resource_identity'].update(occupancy_limit_ctas_per_sm=32),lambda r:r['resource_identity'].update(extensions={'unknown':1})]
        # Drop each complete output component while keeping both declared counts consistent.
        p=case['parameters'];w=p['request_bytes_per_thread']//4;b=original['blocks']
        for missing in (b*128,b*128*p['stages']*w,b*128*8*w):
            def drop(r,n=missing):
                r['checks'][0]['checked_elements']-=n;r['checks'][0]['expected_elements']-=n
            mutations.append(drop)
        for mutation in mutations:
            row=copy.deepcopy(original);mutation(row)
            with self.assertRaises(ValueError):adapter.validate_validation(device,row,case,PROFILE,4294967291)
        for field in original:
            row=copy.deepcopy(original);del row[field]
            with self.assertRaises(ValueError):adapter.validate_validation(device,row,case,PROFILE,4294967291)

    def test_profile_paths_prior_evidence_and_device(self):
        case=CONTRACT['cases'][0]
        for path in ('../probe','/tmp/probe','bin/../probe','bin//probe','bin\\probe'):
            with self.assertRaises(ValueError):adapter.validation_argv(path,case,PROFILE,0)
        for field in PROFILE:
            changed=copy.deepcopy(PROFILE);del changed[field]
            with self.assertRaises(ValueError):adapter.validation_argv('bin/probe',case,changed,0)
        for seed in (-1,2**32,True):
            with self.assertRaises(ValueError):adapter.validation_argv('bin/probe',case,PROFILE,seed)
        request={'case':case,'profile':PROFILE}
        self.assertEqual(adapter.validate_prior_evidence({},request,{})['status'],'insufficient')
        evidence={'source_artifacts_sha256':{'raw.jsonl':'a'*64}}
        self.assertEqual(adapter.validate_prior_evidence(evidence,request,{'raw.jsonl':'a'*64})['status'],'insufficient')
        with self.assertRaises(ValueError):adapter.validate_prior_evidence(evidence,request,{'raw.jsonl':'b'*64})
        _,(device,_)=self.run_host(case)
        for field,value in [('sms',True),('sms',0),('cc','10.0'),('runtime_version',13000),('uuid','wrong'),('registers_per_sm',0)]:
            d=copy.deepcopy(device);d[field]=value
            with self.assertRaises(ValueError):adapter.validate_device(d)

    def test_actual_sass_and_lifecycle_mutations(self):
        text=SASS.read_text();self.assertEqual(len(audit_sass(text,CONTRACT)),24)
        # Delete individual actual instruction lines, including first and second
        # post-wait barriers (consumer/release), so identity rejects omissions.
        part=re.split(r'Function\s*:\s*',text)[1]
        symbol=part.splitlines()[0].strip()
        lines=part.splitlines()
        targets=[]
        for token in ('LDGSTS','LDGDEPBAR','DEPBAR.LE'):
            targets.append(next(line for line in lines if token in line))
        wait_index=next(i for i,line in enumerate(lines) if 'DEPBAR.LE' in line)
        targets += [line for line in lines[wait_index:] if 'BAR.SYNC' in line][:2]
        self.assertEqual(len(targets),5)
        for line in targets:
            with self.assertRaises(ValueError):audit_sass(text.replace(line,'',1),CONTRACT)
        with self.assertRaises(ValueError):audit_sass(text.replace(symbol,symbol+'_wrong',1),CONTRACT)
        with self.assertRaises(ValueError):audit_sass(text.replace('LDGSTS.E.BYPASS.128','LDGSTS.E.128',1),CONTRACT)

    def test_original_device_prefix_unchanged(self):
        original=(REPO/'results/gh200_resource_campaign/20261001-resource-suite-v2/reviews/evidence/S12-source-pre-review/async_copy.r2.cu').read_bytes()
        current=(ROOT/'probes/async_copy.cu').read_bytes()
        self.assertEqual(current.split(b'struct AcCase')[0],original.split(b'struct AcCase')[0])


if __name__=='__main__':unittest.main()
