"""Deterministic bounded fork of immutable S08 source; never modifies its parent."""
from pathlib import Path
import hashlib,re
BASE=Path(__file__).resolve().parents[1]
parent=(BASE/'probes/low_precision.cu').read_text()
assert hashlib.sha256(parent.encode()).hexdigest()=='2b2793915dd136f57c0f7de0aa334595fac93a744e7fc1f87e13abb9629bc2b4'
reference=BASE/'common/low_precision_bounded_fp8_reference_v1.hpp';refhash=hashlib.sha256(reference.read_bytes()).hexdigest()
prefix=parent[:parent.index('// mma/e4m3')]
prefix=prefix.replace('// Generated by generate_low_precision.py. Review generator and regenerate; no CUDA invoked by generation.','// Generated by generate_low_precision_bounded_fp8_v1.py; parent and measured bodies remain frozen.')
prefix=prefix.replace('"../common/low_precision_reference.hpp"','"../common/low_precision_bounded_fp8_reference_v1.hpp"')
prefix=prefix.replace('if(!nonuniform)return Kind==0?0x18:0x2c;', 'if(!nonuniform)return (Kind==0?0x18:0x2c)|(!a&&(inner%2)?0x80:0);')
functions=[]
for kind in ('e4m3','e5m2'):
 for g in (1,2):
  symbol=f'lp_wgmma_{kind}_g{g}';start=parent.index('__global__ void '+symbol+'(');end=parent.index('\n}\n',start)+3
  body=parent[start:end].replace(symbol,'lp_bounded_v1_wgmma_'+kind+f'_g{g}')
  body=body.replace('nonuniform?float(1+group+c)/8:0','nonuniform?float(1+group+c)/8:float(1+2*group+c)/8')
  # Everything after setup's first CTA rendezvous is copied byte-for-byte.
  assert body[body.index('  __syncthreads();'):]==parent[start:end][parent[start:end].index('  __syncthreads();'):]
  functions.append(body)
entries=[]
for kind,k in [('e4m3',0),('e5m2',1)]:
 for g in (1,2):
  for scope in ('one_cta','all_gpu'):
   entries.append(f'  {{"bounded_v1_wgmma_{kind}_g{g}_{scope}",lp_bounded_v1_wgmma_{kind}_g{g},{k},{g},128,{str(scope=="all_gpu").lower()}}},')
host=parent[parent.index('inline std::string lp_difference'):]
host=host.replace('low_precision_reference::','low_precision_bounded_fp8_reference_v1::')
host=host.replace('short_uniform_nonuniform_1_2','bounded_fp8_and_original_nonuniform_1_2_v1')
host=host.replace('low_precision_logical_integer_v1','low_precision_bounded_fp8_logical_v1')
host=host.replace('13345802f9ea6523b42437bdaa5277bca9df5c01add140dcf0b08bff1fe07093',refhash)
host=host.replace('check.nonuniform?"nonuniform":"uniform"','check.nonuniform?"original_seeded_nonuniform_v1":"nonzero_K_alternating_cancellation_v1"')
host=host.replace('low_precision_full_output_integer_reference_v1','low_precision_bounded_fp8_full_output_v1')
host=host.replace('formal uniform; separate seeded 1/2-iteration nonuniform full-output checks; fresh D0','bounded K-alternating FP8; D0=(1+2*group+chain)/8; nonuniform short retains original D0')
host=host.replace('if(validate_only)GH_CUDA(cudaMemset(stamps','GH_CUDA(cudaMemset(stamps')
host=host.replace('if(validate_only) {\n      for(const auto& stamp:o.stamps)','{\n      for(const auto& stamp:o.stamps)')
host=host.replace('if(!std::isfinite(got[i])||got[i]!=expected[i%per_cta])','if(!std::isfinite(got[i])||got[i]!=double(float(got[i]))||got[i]!=expected[i%per_cta]||std::signbit(got[i])!=std::signbit(expected[i%per_cta]))')
host=host.replace('if(!validate_only&&iterations!=8192)', 'if(validate_only&&seed!=3)throw std::runtime_error("short seed must be 3");\n  if(!validate_only&&iterations!=8192)')
# Formal launches do not replay short validation; family B3 admission is external.
a=host.index('  // Correctness-only launches');b=host.index('  auto measured=',a)
host=host[:a]+'  // Formal entry requires external family B3 admission before invocation.\n'+host[b:]
a=host.index('    <<",\\"nonuniform_validation\\":');b=host.index('    <<",\\"input_encoding\\":',a)
host=host[:a]+'''    <<",\\"input_profile_id\\":\\"nonzero_K_alternating_cancellation_v1\\",\\"dynamic_counter_verified\\":false"
    <<",\\"D0_rule\\":\\"(1+2*group+chain)/8\\",\\"nominal_WGMMA_per_group_iteration\\":32"
'''+host[b:]
host=host.replace('    <<",\\\"input_encoding\\\":', '    <<",\\\"bounded_operand_bits\\\":{\\\"A_positive\\\":"<<(c.kind==0?24:44)<<",\\\"B_even\\\":"<<(c.kind==0?24:44)<<",\\\"B_odd\\\":"<<(c.kind==0?152:172)<<"}"\n    <<",\\\"operand_source_form\\\":\\\"SS\\\",\\\"groups_per_CTA\\\":"<<c.groups<<",\\\"chains\\\":2,\\\"batch\\\":16,\\\"wait\\\":0,\\\"shape\\\":[64,64,32]"\n    <<",\\\"input_encoding\\\":')
a=host.index('  if(!wg && c.kind<2)');b=host.index('  gh::emit_trial',a);host=host[:a]+host[b:]
(BASE/'probes/low_precision_bounded_fp8_v1.cu').write_text(prefix+'\n'.join(functions)+'\nconst std::vector<LowCase> cases={\n'+'\n'.join(entries)+'\n};\n'+host)
