#include "../common/probe_runtime.cuh"
#include "../common/tma_stage_request_reference.hpp"
#include "../common/word_artifacts.hpp"
constexpr unsigned ts_Q=16384,ts_W=4096,ts_T=128,ts_G=32;
__device__ __forceinline__ unsigned ts_shared(const void* p){return unsigned(__cvta_generic_to_shared(p));}
__device__ __forceinline__ gh::u64 ts_ns(){gh::u64 x;asm volatile("mov.u64 %0, %%globaltimer;":"=l"(x)::"memory");return x;}
__device__ __forceinline__ gh::u64 ts_cycle(){gh::u64 x;asm volatile("mov.u64 %0, %%clock64;":"=l"(x)::"memory");return x;}
__device__ __forceinline__ gh::u64 ts_wait(unsigned barrier,gh::u64 token,std::uint64_t* failure){gh::u64 start=ts_ns(),attempts=0;for(;;){unsigned done;asm volatile("{ .reg .pred p; mbarrier.try_wait.acquire.cta.shared::cta.b64 p, [%1], %2, 64; selp.b32 %0, 1, 0, p; }":"=r"(done):"r"(barrier),"l"(token):"memory");++attempts;if(done)return attempts;if(ts_ns()-start>=1000000000ull){*reinterpret_cast<volatile std::uint64_t*>(failure)=1;__threadfence();asm volatile("trap;":::"memory");}}}
__device__ __forceinline__ unsigned ts_pattern(bool g2s,unsigned s,unsigned r,unsigned item,unsigned request,unsigned word,unsigned seed){return g2s?17u*unsigned(((gh::u64(blockIdx.x)*ts_G+item%ts_G)*r+request)*ts_W+word)+seed:29u*unsigned(((gh::u64(blockIdx.x)*s+item%s)*r+request)*ts_W+word)+seed;}
// All lanes enter together; completion is already acquired by issuer.
template<unsigned S,unsigned R,bool G2S> __device__ __forceinline__ void ts_retire(unsigned* global,unsigned* tile,unsigned item,unsigned iterations,bool capture,unsigned* trace,std::uint64_t* lifecycle,std::uint64_t* counts){
  const unsigned slot=item%S;__syncthreads(); // issuer acquire/fullwait -> consumer publication
  if(capture){
    if constexpr(!G2S)asm volatile("fence.proxy.async.global;":::"memory");
    for(unsigned index=threadIdx.x;index<R*ts_W;index+=ts_T){const unsigned request=index/ts_W,word=index%ts_W;const gh::u64 offset=((gh::u64(blockIdx.x)*ts_G+item%ts_G)*R+request)*ts_W+word;trace[(gh::u64(blockIdx.x)*iterations+item)*R*ts_W+index]=G2S?reinterpret_cast<volatile unsigned*>(tile)[slot*R*ts_W+index]:reinterpret_cast<volatile unsigned*>(global)[offset];}
    __syncthreads(); // consumer-done gate, distinct from transport publication
  }
  if(threadIdx.x==0){auto* c=counts+gh::u64(blockIdx.x)*12;++c[3];if(capture)++c[4];++c[5];if(capture){auto* e=lifecycle+(gh::u64(blockIdx.x)*iterations+item)*8;e[3]=1;e[4]=1;e[5]=1;}}
  __syncthreads(); // slot-release publication before later reset/issue
}
template<unsigned S,unsigned R,bool G2S> __device__ __forceinline__ void ts_transport(unsigned* global,unsigned iterations,unsigned seed,bool capture,unsigned* trace,unsigned* final_slots,gh::Stamp* stamps,std::uint64_t* counts,std::uint64_t* lifecycle){
 extern __shared__ __align__(16) unsigned char storage[];auto* tile=reinterpret_cast<unsigned*>(storage);constexpr unsigned P=S*R*ts_Q;gh::u64 token0=0,token1=0,token2=0,token3=0;
 for(unsigned index=threadIdx.x;index<S*R*ts_W;index+=ts_T){unsigned slot=index/(R*ts_W),request=(index/ts_W)%R,word=index%ts_W;unsigned value=ts_pattern(G2S,S,R,slot,request,word,seed);tile[index]=G2S?~value:value;}
 if(threadIdx.x==0){for(unsigned slot=0;slot<S;++slot)if constexpr(G2S)asm volatile("mbarrier.init.shared::cta.b64 [%0], 1;"::"r"(ts_shared(storage+P+8*slot)):"memory");for(unsigned field=0;field<12;++field)counts[gh::u64(blockIdx.x)*12+field]=0;counts[gh::u64(blockIdx.x)*12+10]=G2S?S:0;}
 asm volatile("fence.proxy.async.shared::cta;":::"memory");__syncthreads(); // includes init publication
 gh::Stamp stamp{};if(threadIdx.x==0){asm volatile("mov.u32 %0, %%smid;":"=r"(stamp.smid));stamp.begin_ns=ts_ns();stamp.begin_cycle=ts_cycle();}__syncthreads();
 #pragma unroll 1
 for(unsigned item=0;item<iterations;++item){const unsigned slot=item%S;
  if(item>=S){if(threadIdx.x==0){auto* c=counts+gh::u64(blockIdx.x)*12;++c[6];if constexpr(G2S)c[9]+=ts_wait(ts_shared(storage+P+8*slot),(slot==0?token0:slot==1?token1:slot==2?token2:token3),c+8);else asm volatile("cp.async.bulk.wait_group %0;"::"n"(S-1):"memory");}ts_retire<S,R,G2S>(global,tile,item-S,iterations,capture,trace,lifecycle,counts);}
  if(capture){ // Only destination reset; S2G shared source is never poisoned.
   for(unsigned index=threadIdx.x;index<R*ts_W;index+=ts_T){unsigned request=index/ts_W,word=index%ts_W,value=ts_pattern(G2S,S,R,item,request,word,seed);if constexpr(G2S)tile[slot*R*ts_W+index]=~value;else global[((gh::u64(blockIdx.x)*ts_G+item%ts_G)*R+request)*ts_W+word]=~value;}
   if constexpr(G2S)asm volatile("fence.proxy.async.shared::cta;":::"memory");else asm volatile("fence.proxy.async.global;":::"memory");__syncthreads();
  }
  if(threadIdx.x==0){auto* c=counts+gh::u64(blockIdx.x)*12;const unsigned barrier=ts_shared(storage+P+8*slot);if constexpr(G2S)asm volatile("mbarrier.expect_tx.relaxed.cta.shared::cta.b64 [%0], %1;"::"r"(barrier),"r"(R*ts_Q):"memory");
   #pragma unroll
   for(unsigned request=0;request<R;++request){unsigned shared=ts_shared(tile+(slot*R+request)*ts_W);unsigned* source=global+((gh::u64(blockIdx.x)*ts_G+item%ts_G)*R+request)*ts_W;if constexpr(G2S)asm volatile("cp.async.bulk.shared::cta.global.mbarrier::complete_tx::bytes [%0], [%1], %2, [%3];"::"r"(shared),"l"(source),"r"(ts_Q),"r"(barrier):"memory");else asm volatile("cp.async.bulk.global.shared::cta.bulk_group [%0], [%1], %2;"::"l"(source),"r"(shared),"r"(ts_Q):"memory");}
   c[0]+=R;if constexpr(G2S){gh::u64 arrived;asm volatile("mbarrier.arrive.release.cta.shared::cta.b64 %0, [%1];":"=l"(arrived):"r"(barrier):"memory");if(slot==0)token0=arrived;else if(slot==1)token1=arrived;else if(slot==2)token2=arrived;else token3=arrived;++c[2];}else{asm volatile("cp.async.bulk.commit_group;":::"memory");++c[1];}
   if(capture){auto* e=lifecycle+(gh::u64(blockIdx.x)*iterations+item)*8;e[0]=slot;e[1]=item/S;e[2]=G2S?(slot==0?token0:slot==1?token1:slot==2?token2:token3):0;e[3]=0;e[4]=0;e[5]=0;e[6]=R;e[7]=G2S?0:item+1;}
  }__syncthreads();
 }
 if constexpr(!G2S){if(threadIdx.x==0){asm volatile("cp.async.bulk.wait_group 0;":::"memory");counts[gh::u64(blockIdx.x)*12+7]=1;}__syncthreads();}
 for(unsigned item=iterations>S?iterations-S:0;item<iterations;++item){if constexpr(G2S)if(threadIdx.x==0){auto* c=counts+gh::u64(blockIdx.x)*12;c[9]+=ts_wait(ts_shared(storage+P+8*(item%S)),(item%S==0?token0:item%S==1?token1:item%S==2?token2:token3),c+8);}ts_retire<S,R,G2S>(global,tile,item,iterations,capture,trace,lifecycle,counts);}
 __syncthreads();if(threadIdx.x==0){stamp.end_cycle=ts_cycle();stamp.end_ns=ts_ns();stamps[blockIdx.x]=stamp;}
 for(unsigned index=threadIdx.x;index<S*R*ts_W;index+=ts_T)final_slots[gh::u64(blockIdx.x)*S*R*ts_W+index]=tile[index];__syncthreads();
 if constexpr(G2S)if(threadIdx.x==0){for(unsigned slot=0;slot<S;++slot)asm volatile("mbarrier.inval.shared::cta.b64 [%0];"::"r"(ts_shared(storage+P+8*slot)):"memory");counts[gh::u64(blockIdx.x)*12+11]=S;}
}
#define TS_TARGET(S,R) \
extern "C" __global__ void ts_g2s_s##S##_r##R(unsigned* g,unsigned i,unsigned seed,bool capture,unsigned* t,unsigned* f,gh::Stamp* stamps,std::uint64_t* c,std::uint64_t* l){ts_transport<S,R,true>(g,i,seed,capture,t,f,stamps,c,l);} \
extern "C" __global__ void ts_s2g_s##S##_r##R(unsigned* g,unsigned i,unsigned seed,bool capture,unsigned* t,unsigned* f,gh::Stamp* stamps,std::uint64_t* c,std::uint64_t* l){ts_transport<S,R,false>(g,i,seed,capture,t,f,stamps,c,l);}
TS_TARGET(1,1) TS_TARGET(1,2) TS_TARGET(1,4) TS_TARGET(2,1) TS_TARGET(2,2) TS_TARGET(2,4) TS_TARGET(4,1) TS_TARGET(4,2) TS_TARGET(4,4)
struct TsCase{const char* id;unsigned stages,requests;bool g2s,all_gpu;const char* symbol;const void* function;};
#define TS_CASES(S,R) \
 {"gmem_to_smem_16kib_s" #S "_r" #R "_one_cta",S,R,true,false,"ts_g2s_s" #S "_r" #R,reinterpret_cast<const void*>(ts_g2s_s##S##_r##R)}, \
 {"gmem_to_smem_16kib_s" #S "_r" #R "_all_gpu",S,R,true,true,"ts_g2s_s" #S "_r" #R,reinterpret_cast<const void*>(ts_g2s_s##S##_r##R)}, \
 {"smem_to_gmem_16kib_s" #S "_r" #R "_one_cta",S,R,false,false,"ts_s2g_s" #S "_r" #R,reinterpret_cast<const void*>(ts_s2g_s##S##_r##R)}, \
 {"smem_to_gmem_16kib_s" #S "_r" #R "_all_gpu",S,R,false,true,"ts_s2g_s" #S "_r" #R,reinterpret_cast<const void*>(ts_s2g_s##S##_r##R)}
static const TsCase ts_cases[]={TS_CASES(1,1),TS_CASES(1,2),TS_CASES(1,4),TS_CASES(2,1),TS_CASES(2,2),TS_CASES(2,4),TS_CASES(4,1),TS_CASES(4,2),TS_CASES(4,4)};
struct TsArtifact{std::string path,sha;std::vector<gh::u64> shape;};
struct TsCheck{gh::u64 checked=0;std::vector<TsArtifact> artifacts;};
static void ts_save(TsCheck& check,unsigned index,const char* leaf,const std::vector<unsigned>& data,std::vector<gh::u64> shape){gh::u64 count=1;for(auto n:shape)count=tma_stage_reference::mul(count,n);if(count!=data.size())throw std::runtime_error("S16 artifact shape");std::string path="stage_"+std::to_string(index)+"_"+leaf;check.artifacts.push_back({path,word_artifacts::write_words(path,data),shape});}
int main(int argc,char** argv) try {
 const auto device=gh::device();gh::emit_device(device);if(argc==2&&std::string(argv[1])=="device")return 0;
 if(argc!=5||std::string(argv[1])!="validate-only"||std::string(argv[3])!="stage_short_1_2_5_33_v1"||gh::integer(argv[4],0,4294967295ull)!=3)throw std::runtime_error("S16 only validate-only CASE stage_short_1_2_5_33_v1 3; formal admission disabled");
 const TsCase* choice=nullptr;for(const auto& c:ts_cases)if(c.id==std::string(argv[2]))choice=&c;if(!choice)throw std::runtime_error("unknown finite S16 case");const auto& c=*choice;
 const auto shared=tma_stage_reference::shared(c.stages,c.requests);if(shared>device.prop.sharedMemPerBlockOptin)throw std::runtime_error("S16 resource_reject_before_launch: required shared exceeds actual CTA optin capacity");
 GH_CUDA(cudaFuncSetAttribute(c.function,cudaFuncAttributeMaxDynamicSharedMemorySize,shared));cudaFuncAttributes attr{};GH_CUDA(cudaFuncGetAttributes(&attr,c.function));int occupancy=0;GH_CUDA(cudaOccupancyMaxActiveBlocksPerMultiprocessor(&occupancy,c.function,ts_T,shared));if(occupancy<1||attr.localSizeBytes||shared+attr.sharedSizeBytes>device.prop.sharedMemPerBlockOptin)throw std::runtime_error("S16 resource_reject_before_launch: actual attributes/spill/occupancy");
 const unsigned blocks=c.all_gpu?device.prop.multiProcessorCount*std::min(4,occupancy):1;const gh::u64 allocation=tma_stage_reference::allocation(blocks,c.requests),ring_words=(allocation-32)/4,final_words=gh::u64(blocks)*c.stages*c.requests*ts_W,trace_capacity=gh::u64(blocks)*33*c.requests*ts_W,lifecycle_capacity=gh::u64(blocks)*33*8;
 const auto other=tma_stage_reference::mul(trace_capacity+final_words,4)+blocks*sizeof(gh::Stamp)+(gh::u64(blocks)*12+lifecycle_capacity)*8;size_t free_bytes=0,total_bytes=0;GH_CUDA(cudaMemGetInfo(&free_bytes,&total_bytes));if(allocation>free_bytes||other>free_bytes-allocation)throw std::runtime_error("S16 global memory budget");
 unsigned *global=nullptr,*trace=nullptr,*final_slots=nullptr;gh::Stamp* stamps=nullptr;std::uint64_t *counts=nullptr,*lifecycle=nullptr;GH_CUDA(cudaMalloc(&global,allocation));GH_CUDA(cudaMalloc(&trace,trace_capacity*4));GH_CUDA(cudaMalloc(&final_slots,final_words*4));GH_CUDA(cudaMalloc(&stamps,blocks*sizeof(gh::Stamp)));GH_CUDA(cudaMalloc(&counts,blocks*12*8));GH_CUDA(cudaMalloc(&lifecycle,lifecycle_capacity*8));cudaEvent_t end;GH_CUDA(cudaEventCreate(&end));std::vector<TsCheck> checks;const unsigned lengths[]={1,2,5,33};const unsigned seed=3;
 for(unsigned launch=0;launch<4;++launch){unsigned items=lengths[launch];TsCheck check;gh::u64 errors=0;auto compare=[&](unsigned actual,unsigned expected){++check.checked;if(actual!=expected)++errors;};
  std::vector<unsigned> initial(ring_words+8);for(unsigned k=0;k<4;++k){initial[k]=0xd15ea5e0u+k;initial[ring_words+4+k]=0xd15ea5e4u+k;}
  for(gh::u64 index=0;index<ring_words;++index){unsigned b=index/(ts_G*c.requests*ts_W),slot=index/(c.requests*ts_W)%ts_G,request=index/ts_W%c.requests,word=index%ts_W;initial[index+4]=c.g2s?tma_stage_reference::g2s(b,slot,request,word,c.requests,seed):~tma_stage_reference::s2g(b,slot%c.stages,request,word,c.stages,c.requests,seed);}
  GH_CUDA(cudaMemcpy(global,initial.data(),allocation,cudaMemcpyHostToDevice));const auto trace_words=gh::u64(blocks)*items*c.requests*ts_W;std::vector<unsigned> poison(trace_words);
  for(gh::u64 index=0;index<trace_words;++index){unsigned b=index/(items*c.requests*ts_W),item=index/(c.requests*ts_W)%items,request=index/ts_W%c.requests,word=index%ts_W;poison[index]=~(c.g2s?tma_stage_reference::g2s(b,item,request,word,c.requests,seed):tma_stage_reference::s2g(b,item%c.stages,request,word,c.stages,c.requests,seed));}
  GH_CUDA(cudaMemcpy(trace,poison.data(),trace_words*4,cudaMemcpyHostToDevice));std::vector<unsigned> final_poison(final_words);for(gh::u64 index=0;index<final_words;++index){unsigned b=index/(c.stages*c.requests*ts_W),slot=index/(c.requests*ts_W)%c.stages,request=index/ts_W%c.requests,word=index%ts_W;final_poison[index]=~tma_stage_reference::final(c.g2s,b,slot,request,word,c.stages,c.requests,items,seed);}GH_CUDA(cudaMemcpy(final_slots,final_poison.data(),final_words*4,cudaMemcpyHostToDevice));GH_CUDA(cudaMemset(stamps,0xff,blocks*sizeof(gh::Stamp)));GH_CUDA(cudaMemset(counts,0xff,blocks*12*8));GH_CUDA(cudaMemset(lifecycle,0xff,gh::u64(blocks)*items*8*8));
  unsigned* payload=global+4;bool capture=true;unsigned live_seed=seed;void* args[]={&payload,&items,&live_seed,&capture,&trace,&final_slots,&stamps,&counts,&lifecycle};GH_CUDA(cudaLaunchKernel(c.function,dim3(blocks),dim3(ts_T),args,shared));GH_CUDA(cudaEventRecord(end));GH_CUDA(cudaEventSynchronize(end));
  std::vector<unsigned> values(trace_words),finals(final_words),ring(ring_words+8);std::vector<std::uint64_t> ctr(blocks*12),life(gh::u64(blocks)*items*8);std::vector<gh::Stamp> times(blocks);GH_CUDA(cudaMemcpy(values.data(),trace,trace_words*4,cudaMemcpyDeviceToHost));GH_CUDA(cudaMemcpy(finals.data(),final_slots,final_words*4,cudaMemcpyDeviceToHost));GH_CUDA(cudaMemcpy(ring.data(),global,allocation,cudaMemcpyDeviceToHost));GH_CUDA(cudaMemcpy(ctr.data(),counts,blocks*12*8,cudaMemcpyDeviceToHost));GH_CUDA(cudaMemcpy(life.data(),lifecycle,life.size()*8,cudaMemcpyDeviceToHost));GH_CUDA(cudaMemcpy(times.data(),stamps,blocks*sizeof(gh::Stamp),cudaMemcpyDeviceToHost));
  for(gh::u64 i=0;i<trace_words;++i)compare(values[i],~poison[i]);for(gh::u64 i=0;i<final_words;++i)compare(finals[i],~final_poison[i]);for(unsigned k=0;k<4;++k){compare(ring[k],0xd15ea5e0u+k);compare(ring[ring_words+4+k],0xd15ea5e4u+k);}
  for(gh::u64 index=0;index<ring_words;++index){unsigned b=index/(ts_G*c.requests*ts_W),slot=index/(c.requests*ts_W)%ts_G,request=index/ts_W%c.requests,word=index%ts_W;compare(ring[index+4],tma_stage_reference::ring(c.g2s,b,slot,request,word,c.stages,c.requests,items,seed));}
  auto equal64=[&](std::uint64_t actual,std::uint64_t expected){compare(unsigned(actual),unsigned(expected));compare(unsigned(actual>>32),unsigned(expected>>32));};const auto sentinel=std::numeric_limits<gh::u64>::max();std::vector<std::uint64_t> encoded;
  for(unsigned b=0;b<blocks;++b){const auto& t=times[b];if(t.begin_ns==sentinel||t.end_ns==sentinel||t.begin_cycle==sentinel||t.end_cycle==sentinel||t.smid==~unsigned(0)||t.end_ns<t.begin_ns||t.end_cycle<t.begin_cycle)++errors;encoded.insert(encoded.end(),{t.begin_ns,t.end_ns,t.begin_cycle,t.end_cycle,t.smid});check.checked+=10;
   const std::uint64_t expected[]={std::uint64_t(items)*c.requests,c.g2s?0u:items,c.g2s?items:0u,items,items,items,items>c.stages?items-c.stages:0u,c.g2s?0u:1u,0u,0u,c.g2s?c.stages:0u,c.g2s?c.stages:0u};for(unsigned field=0;field<12;++field){const auto actual=ctr[b*12+field];if(field==9&&c.g2s){if(actual<items||actual==sentinel)++errors;check.checked+=2;}else equal64(actual,expected[field]);}
   for(unsigned item=0;item<items;++item){auto* e=life.data()+(gh::u64(b)*items+item)*8;const std::uint64_t expected_life[]={item%c.stages,item/c.stages,0,1,1,1,c.requests,c.g2s?0u:item+1};for(unsigned field=0;field<8;++field){if(field==2&&c.g2s){continue;}equal64(e[field],expected_life[field]);}}
  }
  if(errors)throw std::runtime_error("S16 short full-value/stamp/lifecycle mismatch: "+std::to_string(errors));
  ts_save(check,launch,"trace.u32le",values,{blocks,items,c.requests,ts_W});ts_save(check,launch,"final_slots.u32le",finals,{blocks,c.stages,c.requests,ts_W});ts_save(check,launch,"ring_guards.u32le",ring,{ring_words+8});ts_save(check,launch,"counts.u32le",word_artifacts::split_u64(ctr),{blocks,12,2});ts_save(check,launch,"lifecycle.u32le",word_artifacts::split_u64(life),{blocks,items,8,2});ts_save(check,launch,"stamps.u32le",word_artifacts::split_u64(encoded),{blocks,5,2});checks.push_back(std::move(check));
 }
 const auto reference_sha="0da631ca7585e89cccfb23b804339a0b4ca06c3a6cc37e87e357339a1fa4c6c8";
 std::cout<<"{\"schema_version\":2,\"validation_schema_version\":1,\"type\":\"validation\",\"case_id\":"<<gh::quote(c.id)<<",\"profile_id\":\"stage_short_1_2_5_33_v1\",\"seed\":3,\"scope\":"<<gh::quote(c.all_gpu?"all_gpu":"one_cta")<<",\"threads\":128,\"blocks\":"<<blocks<<",\"errors\":0,\"performance_eligible\":false,\"warmup_executed\":false,\"pilot_executed\":false,\"target_launches\":[";
 for(unsigned k=0;k<4;++k)std::cout<<(k?",":"")<<"{\"launch_index\":"<<k<<",\"iterations\":"<<lengths[k]<<",\"input_profile\":\"nonuniform_uint32_stage_request_pattern\",\"threads\":128,\"blocks\":"<<blocks<<"}";std::cout<<"],\"checks\":[";
 for(unsigned k=0;k<4;++k){const auto& check=checks[k];std::cout<<(k?",":"")<<"{\"launch_index\":"<<k<<",\"reference_model\":\"tma_stage_request_word_reference_v1\",\"reference_sha256\":"<<gh::quote(reference_sha)<<",\"comparison\":\"exact\",\"tolerance_id\":null,\"completed\":true,\"errors\":0,\"checked_elements\":"<<check.checked<<",\"expected_elements\":"<<check.checked<<",\"verified_CTA_ids\":[";for(unsigned b=0;b<blocks;++b)std::cout<<(b?",":"")<<b;std::cout<<"],\"output_artifacts\":[";for(unsigned a=0;a<check.artifacts.size();++a){const auto& item=check.artifacts[a];std::cout<<(a?",":"")<<"{\"path\":"<<gh::quote(item.path)<<",\"sha256\":"<<gh::quote(item.sha)<<",\"dtype\":\"uint32\",\"evidence_kind\":\"full_values\",\"shape\":[";for(unsigned d=0;d<item.shape.size();++d)std::cout<<(d?",":"")<<item.shape[d];std::cout<<"]}";}std::cout<<"]}";}
 std::cout<<"],\"resource_identity\":{\"kernel_symbol\":"<<gh::quote(c.symbol)<<",\"registers_per_thread\":"<<attr.numRegs<<",\"static_smem_bytes\":"<<attr.sharedSizeBytes<<",\"dynamic_smem_bytes\":"<<shared<<",\"local_size_bytes\":"<<attr.localSizeBytes<<",\"occupancy_limit_ctas_per_sm\":"<<occupancy<<",\"extensions\":{\"payload_bytes\":16384,\"software_stages\":"<<c.stages<<",\"requests_per_item\":"<<c.requests<<",\"global_slots_per_cta\":32,\"global_allocation_bytes\":"<<allocation<<",\"capture_enabled\":true,\"opaque_token_evidence\":{\"classification\":\"preserved_domain_only\",\"exact_checked\":false,\"words_per_launch\":[";for(unsigned k=0;k<4;++k)std::cout<<(k?",":"")<<(c.g2s?gh::u64(2)*blocks*lengths[k]:0);std::cout<<"]}}}}\n";
 GH_CUDA(cudaEventDestroy(end));GH_CUDA(cudaFree(lifecycle));GH_CUDA(cudaFree(counts));GH_CUDA(cudaFree(stamps));GH_CUDA(cudaFree(final_slots));GH_CUDA(cudaFree(trace));GH_CUDA(cudaFree(global));return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<'\n';return 2;}
